version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: python:3.9
  redis:
    image: redis:latest