# Generated by Django 4.0.4 on 2023-07-08 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('loan_start_date', models.DateField()),
                ('number_of_payments', models.IntegerField()),
                ('interest_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('days_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('principal', models.FloatField()),
                ('interest', models.FloatField()),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_calculate.credit')),
            ],
        ),
        migrations.AddField(
            model_name='credit',
            name='periodicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_calculate.period'),
        ),
    ]
